// Keyword-to-emoji mapping for travel/packing items
const emojiMap: Record<string, string> = {
  // Hygiene
  toothbrush: "🪥",
  toothpaste: "🦷",
  floss: "🧵",
  shampoo: "🧴",
  conditioner: "🧴",
  soap: "🧼",
  deodorant: "🧴",
  razor: "🪒",
  brush: "💇",
  comb: "💇",
  lotion: "🧴",
  sunscreen: "🧴",
  towel: "🛁",
  nail: "💅",
  makeup: "💄",
  contacts: "👁️",
  glasses: "👓",
  lens: "👁️",
  wipes: "🧻",
  tissue: "🧻",
  cotton: "🩹",
  qtip: "🩹",
  medicine: "💊",
  medication: "💊",
  pills: "💊",
  bandaid: "🩹",
  condoms: "🩲",
  mask: "😷",
  sanitizer: "🧴",
  perfume: "🌸",
  cologne: "🌸",
  moisturizer: "🧴",
  lip: "💄",
  balm: "💄",
  chapstick: "💄",
  shaver: "🪒",
  tweezers: "✂️",
  cottonswab: "🩹",
  cottonswabs: "🩹",
  earplugs: "🦻",
  mouthwash: "🦷",
  retainer: "🦷",
  "shaving cream": "🪒",
  "am lotion": "🌞",
  "pm lotion": "🌙",
  "face cleanser": "🧼",
  batteries: "🔋",
  computer: "💻",
  "battery charger": "🔋",
  "portable battery": "🔋",
  "charging brick": "🔌",
  ibuprofen: "💊",
  "monitor": "🖥️",
  "cable": "🔌",
  "microfiber cloth": "🧽",
  "sim card": "💳",
  "headphones charger": "🔋",
  "power adapter": "🔌",
  "flip flops": "🩴",
  "dress shirt": "👔",
  passport: "🛂",
  suit: "🤵",
  "body wash": "🧴",
  vitamins: "💊",
  // Clothing
  socks: "🧦",
  shoes: "👟",
  sandals: "🩴",
  boots: "🥾",
  flipflops: "🩴",
  underwear: "🩲",
  bra: "👙",
  shirt: "👕",
  "t-shirt": "👕",
  tshirt: "👕",
  pants: "👖",
  jeans: "👖",
  shorts: "🩳",
  dress: "👗",
  skirt: "👗",
  sweater: "🧥",
  jacket: "🧥",
  coat: "🧥",
  hoodie: "🧥",
  raincoat: "🧥",
  umbrella: "☂️",
  hat: "🧢",
  cap: "🧢",
  beanie: "🧢",
  gloves: "🧤",
  scarf: "🧣",
  belt: "🧢",
  pajamas: "🛌",
  swimsuit: "🩱",
  swim: "🩱",
  // Electronics
  charger: "🔌",
  adapter: "🔌",
  converter: "🔌",
  phone: "📱",
  smartphone: "📱",
  laptop: "💻",
  tablet: "💊",
  kindle: "📚",
  earbuds: "🎧",
  earphones: "🎧",
  camera: "📷",
  gopro: "📷",
  battery: "🔋",
  powerbank: "🔋",
  watch: "⌚",
  // Documents
  id: "🪪",
  license: "🪪",
  ticket: "🎫",
  boarding: "🛫",
  visa: "🛃",
  insurance: "📄",
  reservation: "🏨",
  itinerary: "🗺️",
  // Money
  wallet: "👛",
  cash: "💵",
  card: "💳",
  credit: "💳",
  debit: "💳",
  coin: "🪙",
  // Food & Drink
  water: "💧",
  bottle: "🍼",
  snack: "🍫",
  bar: "🍫",
  gum: "🍬",
  candy: "🍬",
  chocolate: "🍫",
  fruit: "🍎",
  apple: "🍎",
  banana: "🍌",
  orange: "🍊",
  sandwich: "🥪",
  chips: "🍟",
  nuts: "🥜",
  // Misc
  book: "📖",
  pen: "🖊️",
  pencil: "✏️",
  notepad: "📒",
  journal: "📓",
  reading: "📖",
  map: "🗺️",
  key: "🔑",
  lock: "🔒",
  bag: "🧳",
  backpack: "🎒",
  suitcase: "🧳",
  pillow: "🛏️",
  blanket: "🛏️",
  sleep: "😴",
  // Health
  bug: "🦟",
  spray: "🦟",
  repellent: "🦟",
  firstaid: "⛑️",
  emergency: "🚨",
  whistle: "🔔",
  flashlight: "🔦",
  torch: "🔦",
  // Travel
  car: "🚗",
  bus: "🚌",
  train: "🚆",
  plane: "✈️",
  flight: "✈️",
  boat: "⛵",
  ferry: "⛴️",
  cruise: "🛳️",
  taxi: "🚕",
  subway: "🚇",
  tram: "🚊",
  bike: "🚲",
  motorcycle: "🏍️",
  scooter: "🛴",
  // Weather
  rain: "🌧️",
  snow: "❄️",
  sun: "☀️",
  sunny: "☀️",
  cloud: "☁️",
  cloudy: "☁️",
  wind: "💨",
  windy: "💨",
  hot: "🥵",
  cold: "🥶",
  humid: "💧",
  // Kids
  diaper: "🧷",
  toy: "🧸",
  pacifier: "🍼",
  stroller: "🛒",
  // Pets
  leash: "🦮",
  bowl: "🥣",
  food: "🍲",
  treat: "🍪",
  // Misc
  gift: "🎁",
  present: "🎁",
  souvenir: "🎁",
  flag: "🏳️",
};

export function getRelevantEmoji(text: string): string | null {
  const lower = text.toLowerCase();
  for (const keyword in emojiMap) {
    if (lower.includes(keyword)) {
      return emojiMap[keyword] ?? null;
    }
  }
  return null;
}
